include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

build-docker-image:
  variables:
    # Build from Datadog Dockerfile and pass the version as Docker build arg
    EXTRA_ARGS: --file=dd.Dockerfile --build-arg=VERSION=${CI_COMMIT_TAG}
  extends: .build-docker-image
