timeout: 3000s
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250116-2a05ea7e3d
    entrypoint: scripts/test-infra/push-image.sh
    env:
    - IMAGE_REGISTRY=gcr.io/$PROJECT_ID
    - _GIT_TAG=$_GIT_TAG
    - HOME=/root
substitutions:
  _GIT_TAG: '0.0.0'
  _PULL_BASE_REF: 'master'
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'
